/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senac.tads.pi1.pigrupo5.view;

import br.senac.tads.pi1.pigrupo5.dao.RelatorioDAO;
import br.senac.tads.pi1.pigrupo5.model.Relatorio;
import br.senac.tads.pi1.pigrupo5.utils.Validador;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bispo
 */
public class BuscaRelatorioFrame extends javax.swing.JFrame {

    Relatorio objRelatorio;

    /**
     * Creates new form ComprasPI
     */
    public BuscaRelatorioFrame() {
        initComponents();
        setLocationRelativeTo(null);
        objRelatorio = new Relatorio();

        CarregarJTableRelatorio("Cod. Pedido", "", null, null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRelatorios = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cbParametro = new javax.swing.JComboBox<>();
        txfBusca = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnVisualizar = new javax.swing.JButton();
        dcInicio = new com.toedter.calendar.JDateChooser();
        dcFim = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Relatório detalhado de vendas"));

        tblRelatorios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod. Pedido", "Cod. Cliente", "Nome", "CPF", "Valor Total", "Valor Desconto", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRelatorios);

        jLabel3.setText("Buscar por:");

        cbParametro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cod. Pedido", "Cod. Cliente", "Nome", "CPF" }));
        cbParametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbParametroActionPerformed(evt);
            }
        });

        txfBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfBuscaKeyTyped(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jLabel1.setText("Data Inicial:");

        jLabel2.setText("Data Final:");

        btnVisualizar.setText("Visualizar");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVisualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(dcInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dcFim, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPesquisar))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbParametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txfBusca)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dcFim, dcInicio});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(cbParametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(dcInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dcFim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVisualizar)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dcFim, dcInicio});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbParametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbParametroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbParametroActionPerformed

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        if (tblRelatorios.getRowCount() > 0) {
            int linha = tblRelatorios.getSelectedRow();

            if (linha >= 0) {
                int idPedido = Integer.parseInt(tblRelatorios.getModel().getValueAt(linha, 0).toString());
                int idCliente = Integer.parseInt(tblRelatorios.getModel().getValueAt(linha, 1).toString());
                String nome = tblRelatorios.getModel().getValueAt(linha, 2).toString();
                String cpf = tblRelatorios.getModel().getValueAt(linha, 3).toString();
                double valorTotal = Double.parseDouble(tblRelatorios.getModel().getValueAt(linha, 4).toString().trim().replace("R$ ", ""));
                double valorDesconto = Double.parseDouble(tblRelatorios.getModel().getValueAt(linha, 5).toString().trim().replace("R$ ", ""));
                String dataPedido = tblRelatorios.getModel().getValueAt(linha, 6).toString();

                objRelatorio.setId(idPedido);
                objRelatorio.setIdCliente(idCliente);
                objRelatorio.setNomeCliente(nome);
                objRelatorio.setCpf(cpf);
                objRelatorio.setTotal(valorTotal);
                objRelatorio.setDesconto(valorDesconto);
                objRelatorio.setDataRelatorio(dataPedido);

                RelatorioFrame relatorioFrame = new RelatorioFrame(objRelatorio);
                relatorioFrame.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um relatório da tabela!");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Não há pedidos para este parametro");
        }
    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        Validador validador = new Validador();
        
        if (validador.CompararData(this.dcInicio, this.dcFim)){
            CarregarJTableRelatorio(cbParametro.getSelectedItem().toString(), txfBusca.getText(), dcInicio.getDate(), dcFim.getDate());
        } else {
            JOptionPane.showMessageDialog(this, "Data Inicial é maior que a final!");
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txfBuscaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfBuscaKeyTyped
        if ((txfBusca.getText() + evt.getKeyChar()).length() > 50) {
            evt.consume();
        }
    }//GEN-LAST:event_txfBuscaKeyTyped

    private void CarregarJTableRelatorio(String parametro, String busca, Date dataInicio, Date dataFim) {
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
        ArrayList<Relatorio> listaRelatorios = RelatorioDAO.consultarRelatorios(parametro, busca, dataInicio, dataFim);
        DefaultTableModel tmRelatorios = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tmRelatorios.addColumn("Cód. Pedido");
        tmRelatorios.addColumn("Cód. Cliente");
        tmRelatorios.addColumn("Nome Cliente");
        tmRelatorios.addColumn("CPF");
        tmRelatorios.addColumn("Valor Total");
        tmRelatorios.addColumn("Valor Desc.");
        tmRelatorios.addColumn("Data");

        tblRelatorios.setModel(tmRelatorios);
        tmRelatorios.setRowCount(0);

        for (Relatorio r : listaRelatorios) {
            tmRelatorios.addRow(new Object[]{r.getId(), r.getIdCliente(), r.getNomeCliente(), r.getCpf(), "R$ " + r.getTotal(), "R$ " + r.getDesconto(), formatador.format(r.getDataPedido())});
        }

        tblRelatorios.getColumnModel().getColumn(0).setPreferredWidth(50); // ID Pedido
        tblRelatorios.getColumnModel().getColumn(1).setPreferredWidth(50); // ID Cliente
        tblRelatorios.getColumnModel().getColumn(2).setPreferredWidth(70); // Nome
        tblRelatorios.getColumnModel().getColumn(3).setPreferredWidth(70); // CPF
        tblRelatorios.getColumnModel().getColumn(4).setPreferredWidth(50); // Valor Total
        tblRelatorios.getColumnModel().getColumn(5).setPreferredWidth(50); // Valor Desconto
        tblRelatorios.getColumnModel().getColumn(6).setPreferredWidth(50); // Data
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscaRelatorioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscaRelatorioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscaRelatorioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscaRelatorioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscaRelatorioFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JComboBox<String> cbParametro;
    private com.toedter.calendar.JDateChooser dcFim;
    private com.toedter.calendar.JDateChooser dcInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRelatorios;
    private javax.swing.JTextField txfBusca;
    // End of variables declaration//GEN-END:variables
}
