

package br.senac.tads.pi1.pigrupo5.view;

import br.senac.tads.pi1.pigrupo5.dao.ProdutoDAO;
import br.senac.tads.pi1.pigrupo5.model.Produto;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;



/**
 *
 * @author wellington
 */
public class BuscarProdutoFrame extends javax.swing.JFrame {
    
     Produto objProduto;

    /**
     * Creates new form BuscarProdutoFrame
     */
    public BuscarProdutoFrame() {
        initComponents();
        DefaultTableModel tabela = (DefaultTableModel) tblProdutos.getModel();
        tblProdutos.setRowSorter(new TableRowSorter(tabela));
        objProduto = new Produto();
        ListaProdutoJtable();
    }
    
    public void ListaProdutoJtable(){
        // mostrar dados do produto na Jtable
        
        DefaultTableModel tabela = (DefaultTableModel) tblProdutos.getModel();
        
        //evitar duplicação ao inserir novo produto
        tabela.setNumRows(0);
        
        ProdutoDAO pdao = new ProdutoDAO();

        for (Produto p: pdao.ListaProduto()){
            
            tabela.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getCodproduto(),
                p.getQtdEstoque(),
                p.getValor(),
                p.getMarca(),
                p.getModelo(),
                p.getCor(),
                p.getCor()
            });
        }
    
    }
    public void ListaProdutoJtableBusca(String busca, String txtParamentro){
        // mostrar dados do produto na Jtable
        
        DefaultTableModel tabela = (DefaultTableModel) tblProdutos.getModel();
        
        //evitar duplicação ao inserir novo produto
        tabela.setNumRows(0);
        
        ProdutoDAO pdao = new ProdutoDAO();

        for (Produto p: pdao.ListaBusca(busca,txtParamentro)){
            
            tabela.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getCodproduto(),
                p.getQtdEstoque(),
                p.getValor(),
                p.getMarca(),
                p.getModelo(),
                p.getCor(),
                p.getCor()
            });
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBusca = new javax.swing.JLabel();
        txtParamentro = new javax.swing.JComboBox<>();
        txtBusca = new javax.swing.JTextField();
        btnPesquisa = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblBusca.setText("Busca por:");

        txtParamentro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código Produto", "Nome" }));
        txtParamentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtParamentroActionPerformed(evt);
            }
        });

        txtBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaActionPerformed(evt);
            }
        });
        txtBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscaKeyTyped(evt);
            }
        });

        btnPesquisa.setText("Pesquisar");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nome", "cód. produto", "qtde estoque", "valor", "marca", "modelo", "cor", "descricao"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProdutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblProdutosKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblProdutos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblBusca)
                            .addGap(18, 18, 18)
                            .addComponent(txtParamentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnPesquisa))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(23, 23, 23)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBusca)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtParamentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtParamentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParamentroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtParamentroActionPerformed

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
    
        String paramentro = "codproduto";
        
        if (txtParamentro.getSelectedItem().toString().equals("Nome")){
            paramentro = "nome";
      
        }
    
        ListaProdutoJtableBusca(txtBusca.getText(),paramentro);
        
        
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
    
        if (tblProdutos.getSelectedRow() != -1){
            
            Produto p = new Produto();
            ProdutoDAO dao = new ProdutoDAO();
            
            p.setId((int)tblProdutos.getValueAt(tblProdutos.getSelectedRow(),0));
            
            dao.Excluir(p);
            
            ListaProdutoJtable();
   
        } else{
        JOptionPane.showMessageDialog(null, "Selecione um produto para excluir");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
      
        if(tblProdutos.getSelectedRow() != -1){
            
         //nome, codproduto, qtdEstoque, valor, marca, modelo, cor, descricao
            int linha = tblProdutos.getSelectedRow();
            int id = Integer.parseInt(tblProdutos.getModel().getValueAt(linha, 0).toString());
            
            String nome = tblProdutos.getModel().getValueAt(linha, 1).toString();
            String codproduto = tblProdutos.getModel().getValueAt(linha, 2).toString();
            String qtdEstoque = tblProdutos.getModel().getValueAt(linha, 3).toString();
            String valor = tblProdutos.getModel().getValueAt(linha, 4).toString();
            String marca = tblProdutos.getModel().getValueAt(linha, 5).toString();
            String modelo = tblProdutos.getModel().getValueAt(linha, 6).toString();
            String cor = tblProdutos.getModel().getValueAt(linha, 7).toString();
            String descricao = tblProdutos.getModel().getValueAt(linha, 8).toString();
            
            objProduto.setId(id);
            objProduto.setNome(nome);
            objProduto.setCodproduto(Integer.parseInt(codproduto));
            objProduto.setQtdEstoque(Integer.parseInt(qtdEstoque));
            objProduto.setValor(Double.parseDouble(valor));
            objProduto.setMarca(marca);
            objProduto.setModelo(modelo);
            objProduto.setCor(cor);
            objProduto.setDescricao(descricao);
            
            CadastroProdutoFrame cadastroproduto = new CadastroProdutoFrame(objProduto);
            cadastroproduto.setVisible(true);
            btnAlterar.setVisible(true);

            
           } else {
            JOptionPane.showMessageDialog(this, "Selecione um produto da tabela!");
        
            
        }
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        CadastroProdutoFrame cadastroproduto = new CadastroProdutoFrame();
        cadastroproduto.setVisible(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaActionPerformed

    private void tblProdutosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblProdutosKeyReleased

       
    }//GEN-LAST:event_tblProdutosKeyReleased

    private void txtBuscaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaKeyTyped
        
        // limitar o numero de entrada de dados
        if(txtBusca.getText().length()>=50){
        evt.consume();
        //tire o comentário abaixo para mostrar o aviso
        //JOptionPane.showMessageDialog(this,"Máximo de 50 caracteres atingido!");
        }
        // para nome permite a entrada de 
        if (txtParamentro.getSelectedItem().toString().equals("Código Produto")){
        char c = evt.getKeyChar();
        if ((c < '0') || (c > '9')){
        evt.consume();
        //JOptionPane.showMessageDialog(null,"Somente números","Entrada de dados",JOptionPane.WARNING_MESSAGE);
        }}
        if (txtParamentro.getSelectedItem().toString().equals("Nome")){
        char c = evt.getKeyChar();
        if ((c < 'a') || (c > 'z')){
        evt.consume();
        //JOptionPane.showMessageDialog(null,"Somente números","Entrada de dados",JOptionPane.WARNING_MESSAGE);
        }}
        

    }//GEN-LAST:event_txtBuscaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarProdutoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarProdutoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarProdutoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarProdutoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarProdutoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBusca;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JComboBox<String> txtParamentro;
    // End of variables declaration//GEN-END:variables
}
