

package br.senac.tads.pi1.pigrupo5.view;

import br.senac.tads.pi1.pigrupo5.dao.ProdutoDAO;
import br.senac.tads.pi1.pigrupo5.model.Produto;
import br.senac.tads.pi1.pigrupo5.utils.Validador;
import javax.swing.JOptionPane;

/**
 *
 * @author wellington
 */
public class CadastroProdutoFrame extends javax.swing.JFrame {
    
    Produto objProduto;
    private int id;
    /**
     * Creates new form CadastroProdutoFramo
     */
     public CadastroProdutoFrame() {
         initComponents();
         objProduto = new Produto();
         //btnsalvar.setVisible(true);
         btnAlterar.setVisible(false);
     }
     
     public CadastroProdutoFrame(Produto p) {
        initComponents();
        this.objProduto = p;
        ////nome, codproduto, qtdEstoque, valor, marca, modelo, cor, descricao
        this.id = p.getId();
        
        this.txtnome.setText(p.getNome());
        this.txtcodproduto.setText(Integer.toString(p.getCodproduto()));
        this.txtqtdeestoque.setText(Integer.toString(p.getQtdEstoque()));
        this.txtvalor.setText(Double.toString(p.getValor()));
        this.txtmarca.setText(p.getMarca());
        this.txtmodelo.setText(p.getModelo());
        this.txtcor.setText(p.getCor());
        this.txtdescricao.setText(p.getDescricao());
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtnome = new javax.swing.JTextField();
        txtcodproduto = new javax.swing.JTextField();
        txtqtdeestoque = new javax.swing.JTextField();
        txtmarca = new javax.swing.JTextField();
        txtmodelo = new javax.swing.JTextField();
        txtvalor = new javax.swing.JFormattedTextField();
        txtcor = new javax.swing.JTextField();
        txtdescricao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnsalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);


        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de produtos"));



        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });
        txtnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnomeKeyTyped(evt);
            }
        });

        txtcodproduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodprodutoKeyTyped(evt);
            }
        });

        txtqtdeestoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqtdeestoqueActionPerformed(evt);
            }
        });
        txtqtdeestoque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtqtdeestoqueKeyTyped(evt);
            }
        });

        txtmarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmarcaKeyTyped(evt);
            }
        });

        txtmodelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmodeloKeyTyped(evt);
            }
        });

        txtvalor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvalorActionPerformed(evt);
            }
        });
        txtvalor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtvalorKeyTyped(evt);
            }
        });

        txtcor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcorActionPerformed(evt);
            }
        });
        txtcor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcorKeyTyped(evt);
            }
        });

        txtdescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdescricaoActionPerformed(evt);
            }
        });
        txtdescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdescricaoKeyTyped(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Qtde estoque:");

        jLabel3.setText("Valor:");

        jLabel4.setText("Cód. produto:");

        jLabel5.setText("Marca:");

        jLabel6.setText("Cor:");

        jLabel7.setText("Modelo:");

        jLabel8.setText("Descrição");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtqtdeestoque, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtcor, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtmarca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtmodelo)
                            .addComponent(txtdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcodproduto)
                            .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcodproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtqtdeestoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtcor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel8))
                    .addComponent(txtdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnsalvar.setText("Salvar");
        btnsalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(btnsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
      
      // chamar produto
      //chamar dao
      Produto p = new Produto();
      ProdutoDAO dao = new ProdutoDAO();
      
      // pegar os valores dos campos
      p.setNome(txtnome.getText());
      p.setCodproduto(Integer.parseInt(txtcodproduto.getText()));
      p.setQtdEstoque(Integer.parseInt(txtqtdeestoque.getText()));
      p.setValor(Double.parseDouble(txtvalor.getText()));
      p.setMarca(txtmarca.getText());
      p.setModelo(txtmodelo.getText());
      p.setCor(txtcor.getText());
      p.setDescricao(txtdescricao.getText());
      
      // Chamar o DAO e passar os dados
      dao.adicionar(p);
      
      // limpar os campos após cadastro
      
      txtnome.setText("");
      txtcodproduto.setText("");
      txtqtdeestoque.setText("");
      txtvalor.setText("");
      txtmarca.setText("");
      txtmodelo.setText("");
      txtcor.setText("");
      txtdescricao.setText("");
      
      ListaProdutoJtable();

    }//GEN-LAST:event_btnsalvarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        
         Produto p = new Produto();
      ProdutoDAO dao = new ProdutoDAO();
      
      // pegar os valores dos campos
      p.setNome(txtnome.getText());
      p.setCodproduto(Integer.parseInt(txtcodproduto.getText()));
      p.setQtdEstoque(Integer.parseInt(txtqtdeestoque.getText()));
      p.setValor(Double.parseDouble(txtvalor.getText()));
      p.setMarca(txtmarca.getText());
      p.setModelo(txtmodelo.getText());
      p.setCor(txtcor.getText());
      p.setDescricao(txtdescricao.getText());
      p.setId(id);
      
      // Chamar o DAO e passar os dados
      dao.atualizar(p);
      
      // limpar os campos após cadastro
      
      txtnome.setText("");
      txtcodproduto.setText("");
      txtqtdeestoque.setText("");
      txtvalor.setText("");
      txtmarca.setText("");
      txtmodelo.setText("");
      txtcor.setText("");
      txtdescricao.setText("");
      
      ListaProdutoJtable();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void txtcorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorActionPerformed

    private void txtdescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescricaoActionPerformed

    private void txtnomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomeKeyTyped
        // TODO add your handling code here:
        // Limitação de 50 caracteres para a marca
        if(txtnome.getText().length()>=50){
        evt.consume();
        JOptionPane.showMessageDialog(this,"Máximo de 50 caracteres atingido!");
        }
    }//GEN-LAST:event_txtnomeKeyTyped

    private void txtqtdeestoqueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtqtdeestoqueKeyTyped
        
        // validação entrada de dados permitindo somente inteiros
//        Validador validar = new Validador();
//        Validador.ValidarInteiro(txtqtdeestoque);
        char c = evt.getKeyChar();
        if ((c < '0') || (c > '9')){
        evt.consume();
        //tire o comentário abaixo para mostrar o aviso
        //JOptionPane.showMessageDialog(null,"Somente números","Entrada de dados",JOptionPane.WARNING_MESSAGE);
        }
        // limitar o numero de entrada de dados
        if(txtqtdeestoque.getText().length()>=5){
        evt.consume();
        //tire o comentário abaixo para mostrar o aviso
        //JOptionPane.showMessageDialog(this,"Máximo de 5 caracteres atingido!");
        }
        
        
    }//GEN-LAST:event_txtqtdeestoqueKeyTyped

    private void txtmarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmarcaKeyTyped
        // TODO add your handling code here:
        
        // limitar o numero de entrada de dados
        if(txtmarca.getText().length()>=50){
        evt.consume();
        //tire o comentário abaixo para mostrar o aviso
        //JOptionPane.showMessageDialog(this,"Máximo de 50 caracteres atingido!");
        }
    }//GEN-LAST:event_txtmarcaKeyTyped

    private void txtcorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcorKeyTyped
        // 
        char c = evt.getKeyChar();
        if ((c < 'a') || (c > 'z')){
        evt.consume();
        //tire o comentário abaixo para mostrar o aviso
        //JOptionPane.showMessageDialog(null,"Somente números","Entrada de dados",JOptionPane.WARNING_MESSAGE);
        }
        // limitar o numero de entrada de dados
        if(txtcodproduto.getText().length()>=20){
        evt.consume();
        //tire o comentário abaixo para mostrar o aviso
        //JOptionPane.showMessageDialog(this,"Máximo de 20 caracteres atingido!");
        }
        
    }//GEN-LAST:event_txtcorKeyTyped

    private void txtcodprodutoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodprodutoKeyTyped
        // TODO add your handling code here:
        
        char c = evt.getKeyChar();
        if ((c < '0') || (c > '9')){
        evt.consume();
        //tire o comentário abaixo para mostrar o aviso
        //JOptionPane.showMessageDialog(null,"Somente números","Entrada de dados",JOptionPane.WARNING_MESSAGE);
        }
        // limitar o numero de entrada de dados
        if(txtcodproduto.getText().length()>=20){
        evt.consume();
        //tire o comentário abaixo para mostrar o aviso
        //JOptionPane.showMessageDialog(this,"Máximo de 20 caracteres atingido!");
        }
    }//GEN-LAST:event_txtcodprodutoKeyTyped

    private void txtmodeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmodeloKeyTyped
        // TODO add your handling code here:
        // limitar o numero de entrada de dados
        if(txtmodelo.getText().length()>=10){
        evt.consume();
        //tire o comentário abaixo para mostrar o aviso
        //JOptionPane.showMessageDialog(this,"Máximo de 10 caracteres atingido!");
        }
        
    }//GEN-LAST:event_txtmodeloKeyTyped

    private void txtdescricaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescricaoKeyTyped
        // TODO add your handling code here:
        if(txtdescricao.getText().length()>=100){
        evt.consume();
        //tire o comentário abaixo para mostrar o aviso
        //JOptionPane.showMessageDialog(this,"Máximo de 100 caracteres atingido!");
        }
        
    }//GEN-LAST:event_txtdescricaoKeyTyped

    private void txtvalorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvalorKeyTyped
        // TODO add your handling code here:
        
        char c = evt.getKeyChar();
        if ((c != '0') && (c != '1') && (c != '2')&& (c != '3') && (c != '4') && (c != '5') && (c != '6') && (c != '7') && (c != '8') && (c != '9') && (c != '.') && (c != ',')  ){
        evt.consume();
        //JOptionPane.showMessageDialog(null,"Somente números","Entrada de dados",JOptionPane.WARNING_MESSAGE);
        }
        
              // limitar o numero de entrada de dados
        if(txtvalor.getText().length()>=8){
        evt.consume();
        //tire o comentário abaixo para mostrar o aviso
        //JOptionPane.showMessageDialog(this,"Máximo de 8 caracteres atingido!");
        }
        
        
    }//GEN-LAST:event_txtvalorKeyTyped

    private void txtvalorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvalorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvalorActionPerformed

    private void txtqtdeestoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqtdeestoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqtdeestoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProdutoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtcodproduto;
    private javax.swing.JTextField txtcor;
    private javax.swing.JTextField txtdescricao;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtmodelo;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtqtdeestoque;
    private javax.swing.JFormattedTextField txtvalor;
    // End of variables declaration//GEN-END:variables

    private void tabelaprodutos() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void ListaProdutoJtable() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
